---

#### Exposure and Outcome ####

exposure_name: "coeliac"
outcome_name: "lymphoma"

#### Disease Codes ####

# list of icd10 codes for the exposures
exposure_codes:
  - "K900"

# list of icd10 disease codes that we want use for our outcome
outcome_codes:
  - "C820"
  - "C821"
  - "C822"
  - "C827"
  - "C829"
  - "C830"
  - "C831"
  - "C832"
  - "C833"
  - "C834"
  - "C835"
  - "C837"
  - "C838"
  - "C839"
  - "C850"
  - "C851"
  - "C857"
  - "C859"
  - "C862"

# GWAS Parameters

# set the p-value threshold for extracting gwas data
p_threshold: 5*10^-8

# set the clumping threshold for LD
clump_threshold: 0.001

#### Provided Filenames ####

# Set the covariates filename
covars_fname: "../data/ukb26390.csv"

# biomarkers filename
biomarkers_fname: "../data/ukb27725.csv"

# Set the filename for the withdrawn participants
withdrawn_fname: "../data/w19266_20200204.csv"

# hospital episode statistics fname
hes_diag_fname: "../data/hesin_diag.txt"

# hospital episode statistics fname
hes_fname: "../data/hesin.txt"

# biomarkers annotation filename
annotation_fname: "../data/Biomarker_annotation.xlsx"

# category codes from the codings showcase
category_codes_fname: "../data/Codings_Showcase.csv"

# data dictionary
data_dict_fname: "../data/data_dictionary.csv"

# genotype data
genotype_fname: "../data/genetic_data_extracted.rds"

# GWAS Marquez raw data
gwas_fname: "../data/Marq.csv"

# gwas principle components filename
gwas_pcs_fname: "../data/GWAS_PCs.rds"

#### Output Filnames ####

# output filename after covariate extraction
covars_output: "../data/covariates.rds"

# output filename for exposures extraction
exposure_output: "../data/exposure.rds"

# output filename after outcome extraction
outcome_output: "../data/outcome.rds"

# output filename after joining cases and covariates
case_covars_output: "../data/case_covars.rds"

# output filename for the iv extraction code
ivs_output: "../data/gwas_ivs.rds"

# output filename for the prs code
prs_output: "../data/coeliac_prs.rds"

#### Configs ####

# Set the filename for the list of field ids
fields_fname: "../configs/covariate_ids.txt"
